# Generated by Django 4.1 on 2022-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_desciption_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
